[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
[theme.customStyles]
    border-radius = "0.5rem"  # <-- This may be misinterpreted if indentation is off
